version: "3"
services:
  vespa:
    image: vespaengine/vespa
    ports:
      - "8080:8080"
      - "5005:5005"
      - "19071:19071"
    volumes:
      - "$PWD:/vespa-sample-apps"
    container_name: vespa
    privileged: true
    hostname: vespa-container
